# Change these first
owner: nishidhjain # Your GitHub organization or username, where this repository lives
repo: upptime-repo # The name of this repository

sites:
  - name: JobDundho
    url: https://jobdundho.com/

status-website:
  baseUrl: /upptime-repo # where "repo" is your repository name
  name: Job Dundho status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
